name: holo

description: "An open source anime tracking app!"

publish_to: "none"

version: 1.1.9+8

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  html: ^0.15.6
  pointycastle: ^3.7.3
  encrypt: ^5.0.3
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  shared_preferences: ^2.5.4
  canvas_danmaku: ^0.3.1
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  screen_brightness: ^2.1.7 # not supported on web linux
  simple_gesture_detector: ^0.2.1
  volume_controller: ^3.4.1 #not supported on web
  cached_network_image: ^3.4.1
  package_info_plus: ^9.0.0
  flutter_cache_manager: ^3.4.1
  easy_localization: ^3.0.8
  shimmer: ^3.0.0
  image_picker: ^1.2.1
  flutter_inappwebview: ^6.1.5
  lottie: ^3.3.2
  flutter_device_type: ^0.4.0 #not supported on web, windows and macos
  window_manager: ^0.5.1 #not supported on web
  flutter_single_instance: ^1.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.4
  build_runner: ^2.4.7 # dart run build_runner build --delete-conflicting-outputs --build-filter=lib/entity/**
  package_rename: ^1.10.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/launcher_round.png
    - lib/assets/translations/
    - lib/assets/lottie/

package_rename_config:
  android:
    app_name: "Holo"
    bundle_name: "Holo"
    package_name: "com.github.qiqd.holo"

  ios:
    app_name: "Holo"
    bundle_name: "Holo"
    package_name: "com.github.qiqd.holo"
  linux:
    app_name: "Holo"
    package_name: "com.github.qiqd.holo"
    exe_name: "Holo"
  macos:
    app_name: "Holo"
    package_name: "com.github.qiqd.holo"
    copyright_notice: "Copyright © 2025"

  windows:
    app_name: "Holo"
    organization: "com.github.qiqd.holo"
    copyright_notice: "Copyright © 2025"
    exe_name: "Holo"
